### ISSUE TITLE
2.1.3 ERROR: ErrorStackParser.parse is not a function

### ISSUE THREAD

**Issue by nzhernovkov** [stacktracejs/error-stack-parser#80]
After upgrading the version to 2.1.3, we get this error.

## Current Behavior
ERROR: ErrorStackParser.parse is not a function

## Your Environment

* Package version: 2.1.3

**Comment by Harry-wyg** [comment]
Looking forward to repairing as soon as possible.

**Comment by elvandiano** [comment]
i hope some one can fixing this bug :(

**Comment by jan-molak** [comment]
Possibly related to https://github.com/stacktracejs/error-stack-parser/issues/75

**Comment by AuspeXeu** [comment]
This breaks all our webpack builds.

**Comment by stevenmhunt** [comment]
I suspect that this change is breaking a lot of people's CI today :( Please roll back this change immediately.

**Comment by Harry-wyg** [comment]
![image](https://user-images.githubusercontent.com/63836723/172201263-c455edb4-2320-476d-937c-c6d0fa1eee37.png)

requirejs has not `module.exports.default`

**Comment by awcs** [comment]
Same here..

**Comment by jonesnc** [comment]
This broke our webpack builds as well.

**Comment by zhouxianjun** [comment]
Now the projects have failed to build, I can compile normally after I force the installation of version 2.0.6

**Comment by jonesnc** [comment]
@nzhernovkov I tried setting ` "error-stack-parser": "2.0.6",` in my `dependencies`, my project also uses `@vue/cli-service` which also depends on `error-stack-parser`, and I'm still getting the error.

Does your project use vue at all? Can you offer any advice?

@eriwen Please revert this change ASAP.

**Comment by zhouxianjun** [comment]
@jonesnc My project uses vue cli, my devDependencies configuration:
```
"@vue/cli-plugin-babel": "~4.5.0",
"@vue/cli-plugin-eslint": "~4.5.0",
"@vue/cli-plugin-router": "~4.5.0",
"@vue/cli-plugin-typescript": "~4.5.0",
"@vue/cli-plugin-vuex": "~4.5.0",
"@vue/cli-service": "~4.5.0",
"error-stack-parser": "2.0.6", // this line fix the error
```

**Comment by danilsdf** [comment]
@zhouxianjun thanks
I have added "error-stack-parser": "2.0.6" to package.json and it fixes it

**Comment by zhouxianjun** [comment]
> @nzhernovkov I tried setting ` "error-stack-parser": "2.0.6",` in my `dependencies`, my project also uses `@vue/cli-service` which also depends on `error-stack-parser`, and I'm still getting the error.
> 
> Does your project use vue at all? Can you offer an advice?
> 
> @eriwen Please revert this change ASAP.

see your package-json.lock 

```
"error-stack-parser": {
  "version": "2.0.6",
  "resolved": "",
  "integrity": "sha1-WpmnB716TFinl5AtSNgoA+3mqtg=",
  "dev": true,
  "requires": {
    "stackframe": "^1.1.1"
  }
}
```

**Comment by Siddharth24Khera** [comment]
@zhouxianjun Adding error-stack-parser 2.0.6 to the devDependencies is leading to 2 versions of it being installed, the first being requested by @soda/friendly-errors-webpack-plugin@^1.7.1 which is a dependency of vue cli service.


```
"@soda/friendly-errors-webpack-plugin@^1.7.1":
  version "1.8.1"
  resolved "https://registry.yarnpkg.com/@soda/friendly-errors-webpack-plugin/-/friendly-errors-webpack-plugin-1.8.1.tgz#4d4fbb1108993aaa362116247c3d18188a2c6c85"
  integrity sha512-h2ooWqP8XuFqTXT+NyAFbrArzfQA7R6HTezADrvD9Re8fxMLTPPniLdqVTdDaO0eIoLaAwKT+d6w+5GeTk7Vbg==
  dependencies:
    chalk "^3.0.0"
    error-stack-parser "^2.0.6"
    string-width "^4.2.3"
    strip-ansi "^6.0.1"

error-stack-parser@2.0.6:
  version "2.0.6"
  resolved "https://registry.yarnpkg.com/error-stack-parser/-/error-stack-parser-2.0.6.tgz#5a99a707bd7a4c58a797902d48d82803ede6aad8"
  integrity sha512-d51brTeqC+BHlwF0BhPtcYgF5nlzf9ZZ0ZIUQNZpc9ZB9qw5IJ2diTrBY9jlCJkTLITYPjmiX6OWCwH+fuyNgQ==
  dependencies:
    stackframe "^1.1.1"

error-stack-parser@^2.0.6:
  version "2.1.3"
  resolved "https://registry.yarnpkg.com/error-stack-parser/-/error-stack-parser-2.1.3.tgz#ab877c676540507dbe6429974ea66833ae68b7cb"
  integrity sha512-F9KypcaAvLzI4yXneZzOvzZoqakhbjuAGFK0aLy33tYaDqdu6v+lzrN/TTG/mM48Op624zZZ2RpXRx3wA0+zmg==
  dependencies:
    stackframe "^1.3.4"
```


**Edit: Found the fix**
For yarn, I used resolutions to force version 2.0.6 

```
 "resolutions": {
    "error-stack-parser": "2.0.6"
  }
```

**Comment by jonesnc** [comment]
@Siddharth24Khera does that `"resolutions"` setting go in the `package.json` file?

**Comment by Siddharth24Khera** [comment]
> @Siddharth24Khera does that `"resolutions"` setting go in the `package.json` file?

Yes,
```
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.4.0",
    "@vue/cli-plugin-eslint": "^3.4.0",
    "@vue/cli-plugin-pwa": "^3.4.0",
    "@vue/cli-service": "^3.4.0",
    "sass": "^1.49.11",
    "sass-loader": "^7.1.0",
    "vue-template-compiler": "^2.6.6",
    "error-stack-parser": "2.0.6"
  },
  "resolutions": {
    "error-stack-parser": "2.0.6"
  }
```

**Comment by jonesnc** [comment]
@Siddharth24Khera Thanks, I think that fixed it for me.

**Comment by Katerinka28** [comment]
> > @Siddharth24Khera does that `"resolutions"` setting go in the `package.json` file?
> 
> Yes,
> 
> ```
>   "devDependencies": {
>     "@vue/cli-plugin-babel": "^3.4.0",
>     "@vue/cli-plugin-eslint": "^3.4.0",
>     "@vue/cli-plugin-pwa": "^3.4.0",
>     "@vue/cli-service": "^3.4.0",
>     "sass": "^1.49.11",
>     "sass-loader": "^7.1.0",
>     "vue-template-compiler": "^2.6.6",
>     "error-stack-parser": "2.0.6"
>   },
>   "resolutions": {
>     "error-stack-parser": "2.0.6"
>   }
> ```
THANK YOU! I tried to fix this by 3 hours...

**Comment by stevenmhunt** [comment]
I've had luck working around this issue by using the new "overrides" functionality in NPM 8.3 or greater: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides Hopefully this issue gets resolved in the actual package itself shortly.

**Comment by ghost** [comment]
Resolvemos esse problemas aplicando ao package.json do projeto:
"resolutions": {
    "error-stack-parser": "2.0.6"
  },
  
 He just solved this issue, applying this in package.json file: 
"resolutions": {
    "error-stack-parser": "2.0.6"
  },

**Comment by logan7000** [comment]
so we should use this version (2.1.3) never?

**Comment by brucemeteor** [comment]
so we should never install this version (2.1.3) ?

**Comment by Katerinka28** [comment]
> so we should never install this version (2.1.3) ?

Hope, `@soda/friendly-errors-webpack-plugin` will fixed import of  `error-stack-parser` as soon as possible. 
They used require(...) by 6 year...

**Comment by s1lentssh** [comment]
Был здесь до того как это стало мемом...

**Comment by titanism** [comment]
We have deprecated v2.1.3, v2.1.2, v2.1.1, v2.1.0, and v3.0.0 using `npm deprecate error-stack-parse@X.X.X "Please upgrade to error-stack-parser >= v2.1.4, see https://github.com/stacktracejs/error-stack-parser/issues/80"`.

@eriwen please use `np` to publish new versions, it will help with versioning and prevent breaking errors.  Also for anything with ESM/CJS changes or import/export changes, we should have done a major semver version release.  See <https://github.com/sindresorhus/np>.

Looking at fixing this unless @eriwen beats us to it.

**Comment by titanism** [comment]
v2.1.4 released to npm and GitHub

https://github.com/stacktracejs/error-stack-parser/releases/tag/v2.1.4
https://www.npmjs.com/package/error-stack-parser/v/2.1.4

@eriwen I reverted those commits that caused the breaking change (when you implement them and upgrade to support both CJS/ESM then perhaps revert and publish a new major semver version).  Note I used `np` to release v2.1.4, and it also makes a nice Release page for us.

**Comment by jan-molak** [comment]
Thanks, @titanism, I can confirm 2.1.4 works for [Serenity/JS](https://github.com/serenity-js) too.

**Comment by eriwen** [comment]
Thanks @titanism for fixing.

I thought I had reverted the breaking commit before releasing 2.1.3. np is a good suggestion I'll use going forward.

**Comment by Archie2035** [comment]
> "error-stack-parser": "2.0.6"
Thanks a lot!

**Comment by Archie2035** [comment]
> 

Thanks a lot!
